version: "3.8"

services:
  nginx:
    build: ./nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
    env_file:
      - .env
  wordpress:
    build: ./wordpress/.
    container_name: wp-php
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
    env_file:
      - .env
  mariadb:
    build: ./mariadb/.
    container_name: mariadb
    command: ["mysqld"]
    networks:
      inception:
    env_file:
      - .env
networks:
  inception: