version: "3.8"

services:
  nginx:
    build: ./nginx/.
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
  wordpress:
    build: ./wordpress/.
    container_name: wp-php
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
  mariadb:
    build: ./mariadb/.
    container_name: mariadb
    command: ["mysqld"]
    networks:
      inception:
networks:
  inception:
